common:
  containerPort: &containerPort "5080"

persistence:
  enabled: true
  size: 10Gi
  storageClass: "gp3-xfs"

config:
  ZO_APP_NAME: "openobserve"
  ZO_CLUSTER_NAME: "o2"
  ZO_INSTANCE_NAME: ""
  ZO_NODE_ROLE: "all"
  ZO_LOCAL_MODE: "true"
  ZO_LOCAL_MODE_STORAGE: "disk"
  ZO_HTTP_PORT: *containerPort
  RUST_LOG: "warning"
  RUST_BACKTRACE: "0"

service:
  type: ClusterIP
  # type: LoadBalancer
  http_port: *containerPort
  # http_nodePort: 30580
  grpc_port: 5081
  # grpc_nodePort: 30581
  annotations: {}

ingress:
  enabled: true
  className: "alb"
  annotations:
    "alb.ingress.kubernetes.io/group.name": "default-alb"
    "alb.ingress.kubernetes.io/group.order": "21"
    "alb.ingress.kubernetes.io/listen-ports": "[{\"HTTP\":80},{\"HTTPS\":443}]"
    "alb.ingress.kubernetes.io/ssl-redirect": "443"
    "alb.ingress.kubernetes.io/target-type": "ip"
    "alb.ingress.kubernetes.io/healthcheck-port": "traffic-port"
    "alb.ingress.kubernetes.io/healthcheck-path": "/healthz"
    "alb.ingress.kubernetes.io/healthy-threshold-count": "3"
    "alb.ingress.kubernetes.io/unhealthy-threshold-count": "5"
  hosts:
    - host: "openobserve.dev.starfort.io"
      paths:
        - path: /
          pathType: Prefix

affinity: {}
nodeSelector:
  "aim-intelligence.com/role": "db"

enterprise:
  enabled: true
  parameters:
    O2_AUDIT_ENABLED: "false"
    O2_AUDIT_BATCH_SIZE: "500"